{
    "name": "Flex Custom fields",
    "version": "1",
    "summary": "Custom velden voor Flex Delivery",
    "category": "",
    "author": "Abstractive BVBA",
    "maintainer": "Abstractive BVBA",
    "website": "https://abstractive.be",
    "license": "OPL-1",
    "depends": ["base", "sale"],
    "data": ["views/sale_order.xml"],
    "installable": True,
    "auto_install": False,
    "application": False,
}
