{
    "name": "Flex-Delivery routes (uitbreidingen)",
    "version": "0.0.1",
    "summary": "Uitbreidingen voor de flex-delivery routes",
    "category": "",
    "author": "Abstractive BVBA",
    "maintainer": "Abstractive BVBA",
    "website": "",
    "license": "",
    "contributors": [""],
    "depends": ["base", "sale", "flex_routes"],
    "data": [
        "views/route_picking_line.xml",
        "views/product_template.xml",
        "security/ir.model.access.csv",
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
}
