{
    "name": "Flex Rapportering",
    "version": "12",
    "summary": "Rapporten voor koeriers, leveranciers & klanten",
    "category": "",
    "author": "Abstractive BVBA",
    "maintainer": "Abstractive BVBA",
    "website": "https://abstractive.be",
    "license": "OPL-1",
    "depends": ["base", "sale", "flex_routes_extensions"],
    "data": [
        "data/euro_a4_format.xml",
        "views/route_picking_report.xml",
        "views/route_picking.xml",
        "views/forecast_report.xml",
        "views/order_report.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
}
