{
    "name": "Flex Sale flows",
    "version": "12.0.0.0.1",
    "summary": "Bevat de nodige code voor de correcte verkoopsflows",
    "category": "",
    "author": "Abstractive BVBA",
    "maintainer": "Abstractive BVBA",
    "website": "https://abstractive.be",
    "license": "Other proprietary",
    "depends": ["base", "sale", "account", "sale_margin"],
    "data": ["data/delivery_notes.xml", "views/res_partner.xml"],
    "installable": True,
    "auto_install": False,
    "application": False,
}
